### ISSUE TITLE
Please add usage doc and how to train a new model from scratch

### ISSUE THREAD

**Issue by tiendung** [ad-freiburg/text-utils#1]
This tool is very interesting. I got the same problem while convert PDF to Text for Vietnamese. I would like to usse `text-correction-utils` to improve the quality. Please support. Thank you! :)

**Comment by bastiscode** [comment]
This repository is not intended to be used for training your own models. Please open a new issue [here](https://github.com/ad-freiburg/whitespace-correction/issues) and I will try to add a guide on how to train your own models in the next couple of days.
